apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: logistic-platform
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/logistic_platform